version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - '5435:5432'
    expose: 
      - '5435'
    volumes: 
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local